apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: minecraft
      protocol: TCP
      name: minecraft
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
